// One-off generator: parses main.html and writes typed data modules for the
// syntax comparison table and the common input-pattern cards.
//
//   node scripts/extract.mjs
//
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')
const html = readFileSync(resolve(root, 'main.html'), 'utf8')

function decode(s) {
  return s
    .replace(/\r\n/g, '\n')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&#39;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
}

function stripTags(s) {
  return decode(
    s
      .replace(/<br\s*\/?>/gi, ' ')
      .replace(/<[^>]+>/g, '')
      .replace(/\s+/g, ' ')
      .trim(),
  )
}

const TONE = { green: 'good', red: 'bad', neutral: 'neutral' }
const LANG_ORDER = ['python', 'csharp', 'typescript', 'rust']

/* ---------------------- syntax comparison table ---------------------- */
function extractSyntaxRows() {
  const tbody = html.slice(
    html.indexOf('<tbody', html.indexOf('syntax-table')),
    html.indexOf('</tbody>'),
  )
  const rows = [...tbody.matchAll(/<tr>([\s\S]*?)<\/tr>/g)].map((m) => m[1])

  return rows.map((row) => {
    const topicMatch = row.match(/<td class="topic-cell[^"]*"[^>]*>([\s\S]*?)<\/td>/)
    const topic = stripTags(topicMatch[1])

    const cells = [
      ...row.matchAll(
        /<td class="(green|red|neutral)-cell">\s*<pre[^>]*><code>([\s\S]*?)<\/code><\/pre>\s*<\/td>/g,
      ),
    ]

    const code = {}
    const tone = {}
    cells.forEach((c, i) => {
      const lang = LANG_ORDER[i]
      tone[lang] = TONE[c[1]]
      code[lang] = decode(c[2])
    })

    return { topic, code, tone }
  })
}

/* ---------------------- input-pattern cards -------------------------- */
function extractInputPatterns() {
  const section = html.slice(
    html.indexOf('id="input-patterns-grid"'),
    html.indexOf('These patterns + the syntax table'),
  )
  const cards = [
    ...section.matchAll(
      /data-lang-card="(python|csharp|typescript|rust)"[\s\S]*?(?=data-lang-card="|$)/g,
    ),
  ]

  return cards.map((m) => {
    const block = m[0]
    const language = m[1]
    const subMatch = block.match(/text-\[10px\][^>]*>([^<]*Most common patterns[^<]*)</)
    const subtitle = subMatch ? stripTags(subMatch[1]) : 'Most common patterns'

    const snippets = [
      ...block.matchAll(
        /<div class="font-mono[^"]*"[^>]*>([\s\S]*?)<\/div>\s*<pre[^>]*><code>([\s\S]*?)<\/code><\/pre>/g,
      ),
    ].map((s) => ({ label: stripTags(s[1]), code: decode(s[2]) }))

    return { language, subtitle, snippets }
  })
}

/* ---------------------- emit ---------------------------------------- */
const header = `// AUTO-GENERATED by scripts/extract.mjs from main.html — do not edit by hand.\n`

const syntaxRows = extractSyntaxRows()
writeFileSync(
  resolve(root, 'src/data/syntaxRows.ts'),
  `${header}import type { SyntaxRow } from '@/types'\n\nexport const SYNTAX_ROWS: SyntaxRow[] = ${JSON.stringify(
    syntaxRows,
    null,
    2,
  )}\n`,
)

const inputPatterns = extractInputPatterns()
writeFileSync(
  resolve(root, 'src/data/inputPatterns.ts'),
  `${header}import type { InputPatternCard } from '@/types'\n\nexport const INPUT_PATTERNS: InputPatternCard[] = ${JSON.stringify(
    inputPatterns,
    null,
    2,
  )}\n`,
)

console.log(
  `Wrote ${syntaxRows.length} syntax rows and ${inputPatterns.length} input-pattern cards.`,
)
