// AUTO-GENERATED by scripts/extract.mjs from main.html — do not edit by hand.
import type { InputPatternCard } from '@/types'

export const INPUT_PATTERNS: InputPatternCard[] = [
  {
    "language": "python",
    "subtitle": "Most common patterns",
    "snippets": [
      {
        "label": "1. Read single int",
        "code": "n = int(input())"
      },
      {
        "label": "2. Read array (n + line)",
        "code": "n = int(input())\narr = list(map(int, input().split()))"
      },
      {
        "label": "3. Read matrix",
        "code": "n, m = map(int, input().split())\nmatrix = [list(map(int, input().split())) for _ in range(n)]"
      },
      {
        "label": "4. Read until EOF / multiple tests",
        "code": "import sys\ndata = sys.stdin.read().strip().split()\n# or line by line\nfor line in sys.stdin:\n    ..."
      },
      {
        "label": "5. Read from file (local test)",
        "code": "with open(\"input.txt\") as f:\n    data = f.read().split()"
      }
    ]
  },
  {
    "language": "csharp",
    "subtitle": "Most common patterns",
    "snippets": [
      {
        "label": "1. Read single int",
        "code": "int n = int.Parse(Console.ReadLine());"
      },
      {
        "label": "2. Read array (n + line)",
        "code": "int n = int.Parse(Console.ReadLine());\nint[] arr = Console.ReadLine().Split().Select(int.Parse).ToArray();"
      },
      {
        "label": "3. Read matrix",
        "code": "var line = Console.ReadLine().Split();\nint n = int.Parse(line[0]), m = int.Parse(line[1]);\nint[,] mat = new int[n, m];\nfor(int i=0; i<n; i++) {\n    var row = Console.ReadLine().Split().Select(int.Parse).ToArray();\n    for(int j=0; j<m; j++) mat[i,j] = row[j];\n}"
      },
      {
        "label": "4. Read until EOF",
        "code": "string line;\nwhile ((line = Console.ReadLine()) != null) { ... }"
      },
      {
        "label": "5. Read from file",
        "code": "string[] data = File.ReadAllLines(\"input.txt\");"
      }
    ]
  },
  {
    "language": "typescript",
    "subtitle": "Most common patterns",
    "snippets": [
      {
        "label": "1. Read single int",
        "code": "const n: number = parseInt(readline());"
      },
      {
        "label": "2. Read array (n + line)",
        "code": "const n = parseInt(readline());\nconst arr = readline().split(' ').map(Number);"
      },
      {
        "label": "3. Read matrix",
        "code": "const [n, m] = readline().split(' ').map(Number);\nconst matrix: number[][] = [];\nfor(let i = 0; i < n; i++) {\n    matrix.push(readline().split(' ').map(Number));\n}"
      },
      {
        "label": "4. Read until EOF (Node)",
        "code": "import * as fs from 'fs';\nconst input = fs.readFileSync(0, 'utf8').trim().split(/\\s+/);"
      },
      {
        "label": "5. Read from file",
        "code": "import * as fs from 'fs';\nconst data = fs.readFileSync('input.txt', 'utf8');"
      }
    ]
  },
  {
    "language": "rust",
    "subtitle": "Most common patterns",
    "snippets": [
      {
        "label": "1. Read single int",
        "code": "let mut input = String::new();\nstd::io::stdin().read_line(&mut input).unwrap();\nlet n: i32 = input.trim().parse().unwrap();"
      },
      {
        "label": "2. Read array (n + line)",
        "code": "let mut s = String::new();\nstd::io::stdin().read_line(&mut s).unwrap();\nlet n: usize = s.trim().parse().unwrap();\nlet arr: Vec<i32> = std::io::stdin()\n    .lock().lines().next().unwrap().unwrap()\n    .split_whitespace().map(|x| x.parse().unwrap()).collect();"
      },
      {
        "label": "3. Read matrix",
        "code": "// Similar: read n, m then loop n times reading lines"
      },
      {
        "label": "4. Read all input at once (recommended)",
        "code": "use std::io::{self, BufRead};\nlet stdin = io::stdin();\nlet mut lines = stdin.lock().lines();\nlet mut nums: Vec<i32> = lines.next().unwrap().unwrap()\n    .split_whitespace().map(|x| x.parse().unwrap()).collect();"
      },
      {
        "label": "5. Read from file",
        "code": "let content = std::fs::read_to_string(\"input.txt\").unwrap();"
      }
    ]
  }
]
