// AUTO-GENERATED by scripts/extract.mjs from main.html — do not edit by hand.
import type { SyntaxRow } from '@/types'

export const SYNTAX_ROWS: SyntaxRow[] = [
  {
    "topic": "Variable Declaration (mutable)",
    "code": {
      "python": "x = 42\n# or with type hint\nx: int = 42",
      "csharp": "int x = 42;\n// or\nvar x = 42;",
      "typescript": "let x: number = 42;\n// or\nlet x = 42;",
      "rust": "let x: i32 = 42;\n// or\nlet x = 42;"
    },
    "tone": {
      "python": "good",
      "csharp": "bad",
      "typescript": "neutral",
      "rust": "bad"
    }
  },
  {
    "topic": "Constants / Immutable Variables",
    "code": {
      "python": "PI = 3.14159\n# Python 3.8+\nfrom typing import Final\nPI: Final = 3.14159",
      "csharp": "const double PI = 3.14159;\n// or readonly\npublic readonly double PI = 3.14159;",
      "typescript": "const PI = 3.14159;\n// or\nconst PI: number = 3.14159;",
      "rust": "const PI: f64 = 3.14159;\n// or\nlet pi = 3.14159; // immutable by default"
    },
    "tone": {
      "python": "good",
      "csharp": "bad",
      "typescript": "neutral",
      "rust": "bad"
    }
  },
  {
    "topic": "Function / Method Definition",
    "code": {
      "python": "def add(a: int, b: int) -> int:\n    return a + b",
      "csharp": "int Add(int a, int b) {\n    return a + b;\n}",
      "typescript": "function add(a: number, b: number): number {\n    return a + b;\n}\n// or arrow\nconst add = (a: number, b: number): number => a + b;",
      "rust": "fn add(a: i32, b: i32) -> i32 {\n    a + b\n}"
    },
    "tone": {
      "python": "good",
      "csharp": "bad",
      "typescript": "neutral",
      "rust": "bad"
    }
  },
  {
    "topic": "Class / Struct + Constructor",
    "code": {
      "python": "class Solution:\n    def __init__(self):\n        self.data: list[int] = []",
      "csharp": "public class Solution {\n    private List<int> data;\n    public Solution() {\n        data = new List<int>();\n    }\n}",
      "typescript": "class Solution {\n    private data: number[] = [];\n    constructor() {}\n}",
      "rust": "struct Solution {\n    data: Vec<i32>,\n}\nimpl Solution {\n    fn new() -> Self {\n        Solution { data: vec![] }\n    }\n}"
    },
    "tone": {
      "python": "good",
      "csharp": "bad",
      "typescript": "neutral",
      "rust": "bad"
    }
  },
  {
    "topic": "Inheritance / Interfaces / Traits",
    "code": {
      "python": "class Animal:\n    def speak(self): pass\n\nclass Dog(Animal):\n    def speak(self): return \"woof\"",
      "csharp": "public interface IAnimal {\n    string Speak();\n}\npublic class Dog : IAnimal {\n    public string Speak() => \"woof\";\n}",
      "typescript": "interface Animal {\n    speak(): string;\n}\nclass Dog implements Animal {\n    speak() { return \"woof\"; }\n}",
      "rust": "trait Animal {\n    fn speak(&self) -> String;\n}\nstruct Dog;\nimpl Animal for Dog {\n    fn speak(&self) -> String {\n        \"woof\".to_string()\n    }\n}"
    },
    "tone": {
      "python": "good",
      "csharp": "bad",
      "typescript": "neutral",
      "rust": "bad"
    }
  },
  {
    "topic": "If / Else Conditional",
    "code": {
      "python": "if x > 0:\n    print(\"positive\")\nelif x == 0:\n    print(\"zero\")\nelse:\n    print(\"negative\")",
      "csharp": "if (x > 0) {\n    Console.WriteLine(\"positive\");\n} else if (x == 0) {\n    Console.WriteLine(\"zero\");\n} else {\n    Console.WriteLine(\"negative\");\n}",
      "typescript": "if (x > 0) {\n    console.log(\"positive\");\n} else if (x === 0) {\n    console.log(\"zero\");\n} else {\n    console.log(\"negative\");\n}",
      "rust": "if x > 0 {\n    println!(\"positive\");\n} else if x == 0 {\n    println!(\"zero\");\n} else {\n    println!(\"negative\");\n}"
    },
    "tone": {
      "python": "good",
      "csharp": "good",
      "typescript": "good",
      "rust": "good"
    }
  },
  {
    "topic": "For Loop (range / collection)",
    "code": {
      "python": "for i in range(10):\n    print(i)\n\nfor num in nums:\n    print(num)",
      "csharp": "for (int i = 0; i < 10; i++) { }\nforeach (int num in nums) { }",
      "typescript": "for (let i = 0; i < 10; i++) { }\nfor (const num of nums) { }",
      "rust": "for i in 0..10 { }\nfor num in &nums { }"
    },
    "tone": {
      "python": "good",
      "csharp": "bad",
      "typescript": "neutral",
      "rust": "bad"
    }
  },
  {
    "topic": "While Loop",
    "code": {
      "python": "while left < right:\n    # logic\n    left += 1",
      "csharp": "while (left < right) {\n    // logic\n    left++;\n}",
      "typescript": "while (left < right) {\n    // logic\n    left++;\n}",
      "rust": "while left < right {\n    // logic\n    left += 1;\n}"
    },
    "tone": {
      "python": "good",
      "csharp": "good",
      "typescript": "good",
      "rust": "good"
    }
  },
  {
    "topic": "Array / List / Vector Init + Access + Length",
    "code": {
      "python": "arr = [1, 2, 3]\narr[0]           # access\nlen(arr)         # length\narr.append(4)",
      "csharp": "int[] arr = {1,2,3};\nList<int> list = new();\nlist.Add(4);\nlist[0]\nlist.Count",
      "typescript": "const arr: number[] = [1,2,3];\narr[0]\narr.length\narr.push(4)",
      "rust": "let arr = vec![1,2,3];\narr[0]\narr.len()\narr.push(4);"
    },
    "tone": {
      "python": "good",
      "csharp": "bad",
      "typescript": "neutral",
      "rust": "bad"
    }
  },
  {
    "topic": "HashMap / Dictionary / Object",
    "code": {
      "python": "d = {\"a\": 1, \"b\": 2}\nd[\"a\"] = 10\nd.get(\"c\", 0)",
      "csharp": "Dictionary<string,int> d = new();\nd[\"a\"] = 1;\nd.TryGetValue(\"c\", out int v);",
      "typescript": "const d: Record<string,number> = {a:1};\nd[\"a\"] = 10;\nd[\"c\"] ?? 0",
      "rust": "use std::collections::HashMap;\nlet mut d = HashMap::new();\nd.insert(\"a\", 1);\nd.get(\"c\").unwrap_or(&0);"
    },
    "tone": {
      "python": "good",
      "csharp": "bad",
      "typescript": "neutral",
      "rust": "bad"
    }
  },
  {
    "topic": "Error Handling",
    "code": {
      "python": "try:\n    risky()\nexcept ValueError as e:\n    print(e)\n# or\nresult = risky() or default",
      "csharp": "try {\n    risky();\n} catch (Exception e) {\n    Console.WriteLine(e);\n}",
      "typescript": "try {\n    risky();\n} catch (e: Error) {\n    console.error(e);\n}",
      "rust": "match risky() {\n    Ok(val) => val,\n    Err(e) => { /* handle */ }\n}\n// or ? operator in fn returning Result"
    },
    "tone": {
      "python": "good",
      "csharp": "bad",
      "typescript": "neutral",
      "rust": "bad"
    }
  },
  {
    "topic": "Imports / Modules / Namespaces",
    "code": {
      "python": "import sys\nfrom collections import deque\nimport numpy as np",
      "csharp": "using System;\nusing System.Collections.Generic;\nusing System.IO;",
      "typescript": "import fs from 'fs';\nimport { readFileSync } from 'fs';",
      "rust": "use std::io::{self, BufRead};\nuse std::collections::{HashMap, VecDeque};"
    },
    "tone": {
      "python": "good",
      "csharp": "bad",
      "typescript": "neutral",
      "rust": "bad"
    }
  },
  {
    "topic": "Program Entry Point (main)",
    "code": {
      "python": "def main():\n    # code here\n\nif __name__ == \"__main__\":\n    main()",
      "csharp": "// Top-level statements (C# 10+)\nConsole.WriteLine(\"Hello\");\n\n// or classic\nstatic void Main(string[] args) { }",
      "typescript": "function main() {\n    // code\n}\nmain();",
      "rust": "fn main() {\n    // code here\n}"
    },
    "tone": {
      "python": "good",
      "csharp": "bad",
      "typescript": "neutral",
      "rust": "bad"
    }
  },
  {
    "topic": "Reading Input (stdin or file)",
    "code": {
      "python": "import sys\ndata = sys.stdin.read().split()\n# or file:\nwith open(\"input.txt\") as f:\n    data = f.read().split()",
      "csharp": "using System;\nstring line = Console.ReadLine();\n// file:\nstring text = File.ReadAllText(\"input.txt\");",
      "typescript": "import * as fs from 'fs';\nconst input = fs.readFileSync(0, 'utf8');\n// or process.stdin",
      "rust": "use std::io::{self, BufRead};\nlet stdin = io::stdin();\nlet mut lines = stdin.lock().lines();\n// file: std::fs::read_to_string(\"input.txt\")"
    },
    "tone": {
      "python": "good",
      "csharp": "bad",
      "typescript": "neutral",
      "rust": "bad"
    }
  },
  {
    "topic": "Efficient String Building",
    "code": {
      "python": "parts = []\nparts.append(\"hello\")\nresult = \"\".join(parts)",
      "csharp": "StringBuilder sb = new();\nsb.Append(\"hello\");\nstring result = sb.ToString();",
      "typescript": "let parts: string[] = [];\nparts.push(\"hello\");\nparts.join(\"\")",
      "rust": "let mut s = String::new();\ns.push_str(\"hello\");\nlet result = s;"
    },
    "tone": {
      "python": "good",
      "csharp": "bad",
      "typescript": "neutral",
      "rust": "bad"
    }
  },
  {
    "topic": "Lambda / Closures",
    "code": {
      "python": "add = lambda a, b: a + b\n# or\ndef make_adder(x):\n    return lambda y: x + y",
      "csharp": "Func<int,int,int> add = (a,b) => a + b;",
      "typescript": "const add = (a: number, b: number) => a + b;",
      "rust": "let add = |a: i32, b: i32| a + b;"
    },
    "tone": {
      "python": "good",
      "csharp": "bad",
      "typescript": "neutral",
      "rust": "bad"
    }
  },
  {
    "topic": "Generics",
    "code": {
      "python": "from typing import TypeVar, Generic\nT = TypeVar('T')\nclass Box(Generic[T]): ...",
      "csharp": "public class Box<T> {\n    public T Value { get; set; }\n}",
      "typescript": "class Box<T> {\n    value: T;\n}",
      "rust": "struct Box<T> {\n    value: T,\n}"
    },
    "tone": {
      "python": "good",
      "csharp": "bad",
      "typescript": "neutral",
      "rust": "bad"
    }
  }
]
